### ISSUE TITLE
土の選択

### ISSUE THREAD

**Issue by kinko173** [prapro-ou/dorodango#21]

**Comment by intan-muzafar** [comment]
https://youtu.be/3qlRgICRoeA

selection scene tutorial

**Comment by intan-muzafar** [comment]
https://youtu.be/3_xHu-JCkl4
car selection scene tutorial

**Comment by intan-muzafar** [comment]
https://youtu.be/smnLYvF40s4

landscape　を作るterrainの tutorial

＊なかなか難しくて、やることはできない。だが、descriptionの場所に役に立つアセットを持つ。
